"""Extraction input-path + prompt template — moved from repo-root
batch_extract_with_claude.py so the extractor (steps/extractors.py) is
package-internal and importable without a repo-root sys.path hack (LT-31).
"""

from pathlib import Path


# Prompt template — markdown content is inlined so Claude reasons over the same
# text the pipeline uses, not a fresh re-parse of the PDF.
EXTRACTION_PROMPT_TEMPLATE = """\
Extract pin electrical specifications from the {part_number} datasheet markdown below.

The markdown was generated from the PDF by MinerU and pdfplumber. Focus on the
Absolute Maximum Ratings, Recommended Operating Conditions, and DC Characteristics
sections. Group pins that share identical electrical specs together.

For SUPPLY voltage extraction (critical):
- Look in "Recommended Operating Conditions" or "Operating Conditions" for the
  nominal supply range (e.g. VCC = 2.0V to 3.6V)
- Look in "Absolute Maximum Ratings" for the supply damage threshold
- For split-supply devices (VCCA/VCCB), give separate groups per supply rail
- Supply voltage range applies to supply pins (VCC/VDD) NOT signal pins

For SIGNAL voltage extraction:
- VIH_min: minimum input voltage that registers as logic HIGH (lower bound)
- VIL_max: maximum input voltage that registers as logic LOW (upper bound)
- VOH_min: minimum output HIGH voltage
- VOL_max: maximum output LOW voltage
- absolute_max_voltage: maximum voltage applicable without damage (from abs max table)

CRITICAL: VIH_min is a LOWER bound. absolute_max_voltage is an UPPER bound.
Never confuse them — they come from different tables.

Numeric fields must be floats in Volts. Use null for values not found.
For non-power groups, leave all four supply_* fields as null.

PROVENANCE: always include the extraction_meta block exactly as shown in the
schema, with "extractor" set to "claude-code", "model" set to the Claude model
you are running as (e.g. claude-opus-4-7), "extracted_at" the current UTC time
in ISO 8601, "source" set to "{source_md}", and "schema_version" 1. Do not
omit this block — it is how provenance is tracked.

Write the result to: {output_path}

Schema:
{{
  "pin_groups": [
    {{
      "group_name": "descriptive name",
      "pin_type": "bidirectional | digital_input | digital_output | power | analog",
      "example_pins": ["A1", "A2", ...],
      "applies_to": "brief description of which pins",
      "VIH_min": null,
      "VIL_max": null,
      "VOH_min": null,
      "VOL_max": null,
      "absolute_max_voltage": null,
      "supply_min": null,
      "supply_max": null,
      "supply_abs_max": null,
      "supply_rail_name": null,
      "VIH_source": "table/section name",
      "abs_max_source": "table/section name"
    }}
  ],
  "default_group": "group_name to use when pin not found in any group",
  "extraction_meta": {{
    "extractor": "claude-code",
    "model": "claude-opus-4-7",
    "extracted_at": "2026-01-01T00:00:00+00:00",
    "source": "{source_md}",
    "schema_version": 1
  }}
}}

--- BEGIN DATASHEET MARKDOWN ---

{markdown_content}

--- END DATASHEET MARKDOWN ---
"""


def extract_pdfplumber_full(pdf_path: Path) -> str:
    """
    Extract markdown from the entire PDF.

    For batch extraction we want complete coverage — electrical
    characteristics may be anywhere (front for simple chips, page 250+
    for ATmega, etc.) so we extract all pages with page break markers.
    """
    import pdfplumber

    with pdfplumber.open(pdf_path) as pdf:
        total = len(pdf.pages)
        print(f"  Extracting all {total} pages")

        sections = []
        for page_num in range(1, total + 1):
            text = pdf.pages[page_num - 1].extract_text() or ""
            if text.strip():
                sections.append(f"\n<!-- page {page_num} -->\n{text}")

        return ("<!-- generated by batch_extract_with_claude.py via pdfplumber -->\n"
                + "\n".join(sections))
